---
# Install bare necessities
# - import_tasks: 1.partition.yml
- import_tasks: 2.filesystems.yml
- import_tasks: 3.mount.yml
- import_tasks: 4.pacstrap.yml
- import_tasks: 5.zoneinfo.yml
- import_tasks: 6.bootctl.yml
- import_tasks: 7.hostname.yml
- import_tasks: 8.locales.yml
- import_tasks: 9.account.yml
- import_tasks: 10.pacman.yml
- import_tasks: 11.grub.yml